title: Valente â€” Data & AI Professional
logo: /assets/img/profile.png
description: Business Analyst | Data Science | AI Solutions | Leadership
remote_theme: pages-themes/dinky@v0.2.0
theme: jekyll-theme-dinky
